version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    # host:container
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      